# Generated by Django 2.2.5 on 2021-03-20 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='responses',
        ),
        migrations.AddField(
            model_name='response',
            name='assignment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='assignment.Assignment'),
            preserve_default=False,
        ),
    ]
