# Generated by Django 2.2.5 on 2021-05-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20210319_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='task',
            field=models.TextField(blank=True, null=True),
        ),
    ]
