# Generated by Django 2.2.5 on 2021-05-25 00:53

import assignment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_auto_20210524_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to=assignment.models.task_directory_path),
        ),
    ]
