# Generated by Django 2.2.5 on 2021-05-25 01:28

import assignment.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_auto_20210524_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='response',
            name='responses',
        ),
        migrations.CreateModel(
            name='ResponseFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfiles', models.FileField(blank=True, upload_to=assignment.models.response_directory_path)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_file', to='assignment.Response')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachments', models.FileField(blank=True, null=True, upload_to=assignment.models.task_directory_path)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_file', to='assignment.Assignment')),
            ],
        ),
    ]
