# Generated by Django 2.2.5 on 2021-11-01 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_auto_20210524_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignment', to='group.Group'),
        ),
    ]
