# Generated by Django 2.2.5 on 2021-06-09 23:03

from django.db import migrations, models


def add_user(apps, schema_editor):
    tasks = apps.get_model('todo', 'TodoTasks')
    User = apps.get_model('auth.User')

    for task in tasks.objects.all():
        user = User.objects.filter(username='asus').first()
        task.user = user
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210609_1602'),
    ]

    operations = [
        migrations.RunPython(
            add_user, reverse_code=migrations.RunPython.noop,),
        # this allows rewinding the migrations to a previous
        # state by skipping this custom migration script
    ]
