# Generated by Django 2.2.5 on 2021-06-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210617_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotasks',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
