# Generated by Django 2.2.5 on 2021-03-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20210319_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
