# Generated by Django 2.2.5 on 2021-05-10 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiztest',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='quiztest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quiztest',
            name='user_submitted',
        ),
        migrations.CreateModel(
            name='UserQuizInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_submitted', models.BooleanField(default=False)),
                ('mark', models.PositiveIntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizTest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
