# Generated by Django 2.2.5 on 2021-05-15 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210510_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztest',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_quiz', to='group.Group'),
        ),
    ]
