# Generated by Django 2.2.5 on 2021-05-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210515_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztest',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
