# Generated by Django 2.2.5 on 2021-05-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_question_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztest',
            name='test_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiztest',
            name='test_starttime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
