# Generated by Django 2.2.5 on 2021-11-18 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20210519_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizinfo',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_info', to='quiz.QuizTest'),
        ),
    ]
